title: Shadow Evol
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.375
  brandStrength: 0.5
  rhythmicContrast: 1
  brandColors:
    - '#FE0000'
    - '#000000'
    - '#0ED4CD'
    - '#F4C00B'
    - '#CC02B2'
  lightness: 0.625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Shadow Evol '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.75552
layout_spectrum: 0.546595
