collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2204301
  brandStrength: 0.8297491
  lightness: 0.3243728
  brandColors:
    - '#FE0000'
    - '#000000'
    - '#0ED4CD'
    - '#F4C00B'
    - '#CC02B2'
  rhythmicContrast: 0.6326165
typography_spectrum: 0.7759857
layout_spectrum: 0.9480287
name: 'Shadowevol '
