collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4964158
  brandStrength: 0.8297491
  lightness: 0.3978495
  brandColors:
    - '#ACA390'
    - '#051415'
    - '#774B28'
    - '#ACA302'
    - '#D0D8F4'
  rhythmicContrast: 0.4551971
typography_spectrum: 0.7759857
layout_spectrum: 0.9480287
name: 'Shadowevol '
