title: Shadow Evol
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.5
  lightness: 0.3125
  brandColors:
    - '#FFFFFF'
    - '#055075'
    - '#5E8CA4'
    - '#9BC2E4'
    - '#0A0A08'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Shadow Evol '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85542
layout_spectrum: 1
